// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	models.proto

It has these top-level messages:
	User
	Teammate
	Collection
	AuthToken
	Session
	Pageview
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	ID               uint64 `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Email            string `protobuf:"bytes,2,opt,name=Email,json=email" json:"Email,omitempty"`
	Password         string `protobuf:"bytes,3,opt,name=Password,json=password" json:"Password,omitempty"`
	Created          int64  `protobuf:"varint,4,opt,name=Created,json=created" json:"Created,omitempty"`
	Name             string `protobuf:"bytes,5,opt,name=Name,json=name" json:"Name,omitempty"`
	IsAdmin          bool   `protobuf:"varint,10,opt,name=IsAdmin,json=isAdmin" json:"IsAdmin,omitempty"`
	DisablePwChange  bool   `protobuf:"varint,11,opt,name=DisablePwChange,json=disablePwChange" json:"DisablePwChange,omitempty"`
	LimitCollections bool   `protobuf:"varint,12,opt,name=LimitCollections,json=limitCollections" json:"LimitCollections,omitempty"`
	CollectionLimit  uint32 `protobuf:"varint,13,opt,name=CollectionLimit,json=collectionLimit" json:"CollectionLimit,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetDisablePwChange() bool {
	if m != nil {
		return m.DisablePwChange
	}
	return false
}

func (m *User) GetLimitCollections() bool {
	if m != nil {
		return m.LimitCollections
	}
	return false
}

func (m *User) GetCollectionLimit() uint32 {
	if m != nil {
		return m.CollectionLimit
	}
	return 0
}

type Teammate struct {
	ID uint64 `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
}

func (m *Teammate) Reset()                    { *m = Teammate{} }
func (m *Teammate) String() string            { return proto.CompactTextString(m) }
func (*Teammate) ProtoMessage()               {}
func (*Teammate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Teammate) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type Collection struct {
	ID        string      `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	OwnerID   uint64      `protobuf:"varint,2,opt,name=OwnerID,json=ownerID" json:"OwnerID,omitempty"`
	Name      string      `protobuf:"bytes,3,opt,name=Name,json=name" json:"Name,omitempty"`
	Teammates []*Teammate `protobuf:"bytes,4,rep,name=Teammates,json=teammates" json:"Teammates,omitempty"`
	Created   int64       `protobuf:"varint,5,opt,name=Created,json=created" json:"Created,omitempty"`
}

func (m *Collection) Reset()                    { *m = Collection{} }
func (m *Collection) String() string            { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()               {}
func (*Collection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Collection) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Collection) GetOwnerID() uint64 {
	if m != nil {
		return m.OwnerID
	}
	return 0
}

func (m *Collection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Collection) GetTeammates() []*Teammate {
	if m != nil {
		return m.Teammates
	}
	return nil
}

func (m *Collection) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type AuthToken struct {
	ID      string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	OwnerID uint64 `protobuf:"varint,2,opt,name=OwnerID,json=ownerID" json:"OwnerID,omitempty"`
	TTL     int32  `protobuf:"varint,3,opt,name=TTL,json=tTL" json:"TTL,omitempty"`
	Created int64  `protobuf:"varint,4,opt,name=Created,json=created" json:"Created,omitempty"`
}

func (m *AuthToken) Reset()                    { *m = AuthToken{} }
func (m *AuthToken) String() string            { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()               {}
func (*AuthToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthToken) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AuthToken) GetOwnerID() uint64 {
	if m != nil {
		return m.OwnerID
	}
	return 0
}

func (m *AuthToken) GetTTL() int32 {
	if m != nil {
		return m.TTL
	}
	return 0
}

func (m *AuthToken) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type Session struct {
	Duration         int32  `protobuf:"varint,1,opt,name=Duration,json=duration" json:"Duration,omitempty"`
	Hostname         string `protobuf:"bytes,2,opt,name=Hostname,json=hostname" json:"Hostname,omitempty"`
	DeviceOS         string `protobuf:"bytes,3,opt,name=DeviceOS,json=deviceOS" json:"DeviceOS,omitempty"`
	BrowserName      string `protobuf:"bytes,4,opt,name=BrowserName,json=browserName" json:"BrowserName,omitempty"`
	BrowserVersion   string `protobuf:"bytes,5,opt,name=BrowserVersion,json=browserVersion" json:"BrowserVersion,omitempty"`
	BrowserLanguage  string `protobuf:"bytes,6,opt,name=BrowserLanguage,json=browserLanguage" json:"BrowserLanguage,omitempty"`
	ScreenResolution string `protobuf:"bytes,7,opt,name=ScreenResolution,json=screenResolution" json:"ScreenResolution,omitempty"`
	WindowResolution string `protobuf:"bytes,8,opt,name=WindowResolution,json=windowResolution" json:"WindowResolution,omitempty"`
	DeviceType       string `protobuf:"bytes,9,opt,name=DeviceType,json=deviceType" json:"DeviceType,omitempty"`
	CountryCode      string `protobuf:"bytes,10,opt,name=CountryCode,json=countryCode" json:"CountryCode,omitempty"`
	City             string `protobuf:"bytes,11,opt,name=City,json=city" json:"City,omitempty"`
	UserAgent        string `protobuf:"bytes,12,opt,name=UserAgent,json=userAgent" json:"UserAgent,omitempty"`
	UserIP           string `protobuf:"bytes,13,opt,name=UserIP,json=userIP" json:"UserIP,omitempty"`
	UserHostname     string `protobuf:"bytes,14,opt,name=UserHostname,json=userHostname" json:"UserHostname,omitempty"`
	Referrer         string `protobuf:"bytes,15,opt,name=Referrer,json=referrer" json:"Referrer,omitempty"`
	ASNumber         int32  `protobuf:"varint,16,opt,name=ASNumber,json=aSNumber" json:"ASNumber,omitempty"`
	ASName           string `protobuf:"bytes,17,opt,name=ASName,json=aSName" json:"ASName,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Session) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Session) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Session) GetDeviceOS() string {
	if m != nil {
		return m.DeviceOS
	}
	return ""
}

func (m *Session) GetBrowserName() string {
	if m != nil {
		return m.BrowserName
	}
	return ""
}

func (m *Session) GetBrowserVersion() string {
	if m != nil {
		return m.BrowserVersion
	}
	return ""
}

func (m *Session) GetBrowserLanguage() string {
	if m != nil {
		return m.BrowserLanguage
	}
	return ""
}

func (m *Session) GetScreenResolution() string {
	if m != nil {
		return m.ScreenResolution
	}
	return ""
}

func (m *Session) GetWindowResolution() string {
	if m != nil {
		return m.WindowResolution
	}
	return ""
}

func (m *Session) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *Session) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Session) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Session) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *Session) GetUserIP() string {
	if m != nil {
		return m.UserIP
	}
	return ""
}

func (m *Session) GetUserHostname() string {
	if m != nil {
		return m.UserHostname
	}
	return ""
}

func (m *Session) GetReferrer() string {
	if m != nil {
		return m.Referrer
	}
	return ""
}

func (m *Session) GetASNumber() int32 {
	if m != nil {
		return m.ASNumber
	}
	return 0
}

func (m *Session) GetASName() string {
	if m != nil {
		return m.ASName
	}
	return ""
}

type Pageview struct {
	Path        string `protobuf:"bytes,1,opt,name=Path,json=path" json:"Path,omitempty"`
	QueryString string `protobuf:"bytes,2,opt,name=QueryString,json=queryString" json:"QueryString,omitempty"`
}

func (m *Pageview) Reset()                    { *m = Pageview{} }
func (m *Pageview) String() string            { return proto.CompactTextString(m) }
func (*Pageview) ProtoMessage()               {}
func (*Pageview) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Pageview) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Pageview) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "db.User")
	proto.RegisterType((*Teammate)(nil), "db.Teammate")
	proto.RegisterType((*Collection)(nil), "db.Collection")
	proto.RegisterType((*AuthToken)(nil), "db.AuthToken")
	proto.RegisterType((*Session)(nil), "db.Session")
	proto.RegisterType((*Pageview)(nil), "db.Pageview")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x8e, 0xda, 0x3c,
	0x14, 0x55, 0x20, 0x90, 0xc4, 0x30, 0xc0, 0x67, 0x7d, 0xaa, 0xac, 0x51, 0x55, 0x45, 0x59, 0x54,
	0xd1, 0x2c, 0x66, 0xd1, 0xbe, 0x40, 0x29, 0x54, 0x2a, 0x12, 0x9a, 0xa1, 0x86, 0xb6, 0x6b, 0x27,
	0xb9, 0x05, 0xab, 0x49, 0x4c, 0x6d, 0x67, 0x22, 0xde, 0x62, 0x5e, 0xa3, 0x6f, 0x59, 0xd9, 0x09,
	0xc3, 0x8f, 0xd4, 0x45, 0x97, 0xe7, 0xdc, 0xe3, 0x5c, 0xdf, 0x73, 0x4f, 0x8c, 0x86, 0x85, 0xc8,
	0x20, 0x57, 0xf7, 0x7b, 0x29, 0xb4, 0xc0, 0x9d, 0x2c, 0x89, 0x9e, 0x3b, 0xc8, 0xfd, 0xaa, 0x40,
	0xe2, 0x11, 0xea, 0x2c, 0xe6, 0xc4, 0x09, 0x9d, 0xd8, 0xa5, 0x1d, 0x3e, 0xc7, 0xff, 0xa3, 0xde,
	0xa7, 0x82, 0xf1, 0x9c, 0x74, 0x42, 0x27, 0x0e, 0x68, 0x0f, 0x0c, 0xc0, 0xb7, 0xc8, 0x5f, 0x31,
	0xa5, 0x6a, 0x21, 0x33, 0xd2, 0xb5, 0x05, 0x7f, 0xdf, 0x62, 0x4c, 0x90, 0x37, 0x93, 0xc0, 0x34,
	0x64, 0xc4, 0x0d, 0x9d, 0xb8, 0x4b, 0xbd, 0xb4, 0x81, 0x18, 0x23, 0xf7, 0x81, 0x15, 0x40, 0x7a,
	0xf6, 0x84, 0x5b, 0xb2, 0x02, 0x8c, 0x7a, 0xa1, 0xa6, 0x59, 0xc1, 0x4b, 0x82, 0x42, 0x27, 0xf6,
	0xa9, 0xc7, 0x1b, 0x88, 0x63, 0x34, 0x9e, 0x73, 0xc5, 0x92, 0x1c, 0x56, 0xf5, 0x6c, 0xc7, 0xca,
	0x2d, 0x90, 0x81, 0x55, 0x8c, 0xb3, 0x4b, 0x1a, 0xdf, 0xa1, 0xc9, 0x92, 0x17, 0x5c, 0xcf, 0x44,
	0x9e, 0x43, 0xaa, 0xb9, 0x28, 0x15, 0x19, 0x5a, 0xe9, 0x24, 0xbf, 0xe2, 0xcd, 0x57, 0x4f, 0xd0,
	0x9e, 0x22, 0x37, 0xa1, 0x13, 0xdf, 0xd0, 0x71, 0x7a, 0x49, 0x47, 0xb7, 0xc8, 0xdf, 0x00, 0x2b,
	0x0a, 0xa6, 0xe1, 0xda, 0x95, 0xe8, 0xd9, 0x41, 0xe8, 0xf4, 0x99, 0xb3, 0x72, 0x60, 0x4d, 0x23,
	0xc8, 0x7b, 0xac, 0x4b, 0x90, 0x8b, 0xb9, 0xb5, 0xcd, 0xa5, 0x9e, 0x68, 0xe0, 0x8b, 0x05, 0xdd,
	0x33, 0x0b, 0xee, 0x50, 0x70, 0x6c, 0xa4, 0x88, 0x1b, 0x76, 0xe3, 0xc1, 0xbb, 0xe1, 0x7d, 0x96,
	0xdc, 0x1f, 0x49, 0x1a, 0xe8, 0x63, 0xf9, 0xdc, 0xdc, 0xde, 0x85, 0xb9, 0x11, 0x43, 0xc1, 0xb4,
	0xd2, 0xbb, 0x8d, 0xf8, 0x09, 0xff, 0x72, 0xa1, 0x09, 0xea, 0x6e, 0x36, 0x4b, 0x7b, 0x9f, 0x1e,
	0xed, 0xea, 0xcd, 0xf2, 0xef, 0xfb, 0x8b, 0x7e, 0xbb, 0xc8, 0x5b, 0x83, 0x52, 0x66, 0xe4, 0x5b,
	0xe4, 0xcf, 0x2b, 0xc9, 0xcc, 0xf8, 0xb6, 0x4f, 0x8f, 0xfa, 0x59, 0x8b, 0x4d, 0xed, 0xb3, 0x50,
	0xda, 0x0c, 0xd7, 0xc6, 0xc6, 0xdf, 0xb5, 0xd8, 0x9e, 0x83, 0x27, 0x9e, 0xc2, 0xe3, 0xfa, 0x98,
	0x9c, 0xac, 0xc5, 0x38, 0x44, 0x83, 0x8f, 0x52, 0xd4, 0x0a, 0xa4, 0xf5, 0xc8, 0xb5, 0xe5, 0x41,
	0x72, 0xa2, 0xf0, 0x5b, 0x34, 0x6a, 0x15, 0xdf, 0x40, 0x9a, 0x7b, 0xb4, 0x59, 0x1a, 0x25, 0x17,
	0xac, 0xd9, 0x72, 0xab, 0x5b, 0xb2, 0x72, 0x5b, 0xb1, 0x2d, 0x90, 0xbe, 0x15, 0x8e, 0x93, 0x4b,
	0xda, 0x64, 0x67, 0x9d, 0x4a, 0x80, 0x92, 0x82, 0x12, 0x79, 0x65, 0xe7, 0xf1, 0xac, 0x74, 0xa2,
	0xae, 0x78, 0xa3, 0xfd, 0xce, 0xcb, 0x4c, 0xd4, 0x67, 0x5a, 0xbf, 0xd1, 0xd6, 0x57, 0x3c, 0x7e,
	0x83, 0x50, 0x33, 0xe7, 0xe6, 0xb0, 0x07, 0x12, 0x58, 0x15, 0xca, 0x5e, 0x18, 0x33, 0xeb, 0x4c,
	0x54, 0xa5, 0x96, 0x87, 0x99, 0xc8, 0xc0, 0x66, 0x3f, 0xa0, 0x83, 0xf4, 0x44, 0x99, 0xa8, 0xcc,
	0xb8, 0x3e, 0xd8, 0xd0, 0x07, 0xd4, 0x4d, 0xb9, 0x3e, 0xe0, 0xd7, 0x28, 0x30, 0x7f, 0xe9, 0x74,
	0x0b, 0xa5, 0xb6, 0x11, 0x0f, 0x68, 0x50, 0x1d, 0x09, 0xfc, 0x0a, 0xf5, 0x4d, 0x75, 0xb1, 0xb2,
	0x91, 0x0e, 0x68, 0xbf, 0xb2, 0x08, 0x47, 0x68, 0x68, 0xf8, 0x97, 0x9d, 0x8c, 0x6c, 0x75, 0x58,
	0x9d, 0x71, 0x66, 0x2f, 0x14, 0x7e, 0x80, 0x94, 0x20, 0xc9, 0xb8, 0xd9, 0x8b, 0x6c, 0xb1, 0xa9,
	0x4d, 0xd7, 0x0f, 0x55, 0x91, 0x80, 0x24, 0x93, 0x66, 0xd7, 0xac, 0xc5, 0xa6, 0xe7, 0x74, 0x6d,
	0xd7, 0xf5, 0x5f, 0xd3, 0x93, 0x59, 0x14, 0x7d, 0x30, 0x2f, 0xc4, 0x16, 0x9e, 0x38, 0xd4, 0x66,
	0x92, 0x15, 0xd3, 0xbb, 0x36, 0x8f, 0xee, 0x9e, 0xe9, 0x9d, 0x99, 0xff, 0x4b, 0x05, 0xf2, 0xb0,
	0xd6, 0x92, 0x97, 0xdb, 0x36, 0x26, 0x83, 0x5f, 0x27, 0x2a, 0xe9, 0xdb, 0xd7, 0xe9, 0xfd, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x88, 0x5b, 0xe1, 0xad, 0x04, 0x00, 0x00,
}
